import os
import sys
from pathlib import Path
from typing import Dict, Any, Optional

# Add project root to sys.path so backend imports resolve cleanly
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from fastapi import FastAPI, Request, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, StreamingResponse
from pydantic import BaseModel

from backend.engine.agent_graph import VeritasAgentGraph
from backend.engine.file_parser import ResearchFileParser

app = FastAPI(
    title="Veritas: Autonomous Deep-Research & Fact-Checking Engine API",
    version="1.0.0",
    description="Multi-agent investigative fact-checking engine powered by LangGraph, DuckDuckGo, and adversarial verification."
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

BENCHMARK_PAPERS = [
    {
        "id": "deepseek_r1",
        "filename": "DeepSeek_R1_Reasoning_via_RL.pdf",
        "title": "DeepSeek-R1: Incentivizing Reasoning Capability in LLMs via Reinforcement Learning",
        "authors": "DeepSeek-AI Team (Daya Guo, Dejian Yang, Haowei Zhang et al.)",
        "venue": "arXiv:2501.12948 (Jan 2025)",
        "badge": "Reasoning & RL",
        "page_count": 28,
        "word_count": 14200,
        "abstract_summary": "We introduce DeepSeek-R1-Zero and DeepSeek-R1, models trained via large-scale reinforcement learning (RL) without supervised fine-tuning (SFT) as a preliminary step. DeepSeek-R1-Zero naturally develops capabilities including self-verification, reflection, and generating long chains of thought. On reasoning benchmarks, DeepSeek-R1 achieves 79.8% pass@1 on AIME 2024 and 97.3% on MATH-500, rivaling OpenAI-o1-1217.",
        "key_assertions": [
            "Pure reinforcement learning without initial supervised fine-tuning successfully induces advanced reasoning behaviors such as self-correction and multi-step verification.",
            "DeepSeek-R1 matches OpenAI-o1-1217 performance on competitive mathematics (79.8% pass@1 on AIME 2024).",
            "Distillation from deep reasoning models into smaller dense models (1.5B to 70B) outperforms direct RL training on smaller architectures.",
            "Rejection sampling combined with multi-stage RL prevents model degeneration and language-mixing phenomena."
        ],
        "suggested_query": "DeepSeek-R1 pure reinforcement learning reasoning self-verification matches OpenAI o1 benchmarks",
        "preview": "This paper presents DeepSeek-R1, an open-weights reasoning model trained via large-scale RL..."
    },
    {
        "id": "lk99_superconductor",
        "filename": "LK99_First_Room_Temperature_Ambient_Superconductor.pdf",
        "title": "The First Room-Temperature Ambient-Pressure Superconductor (LK-99)",
        "authors": "Sukbae Lee, Ji-Hoon Kim, Young-Wan Kwon (Quantum Energy Research Centre)",
        "venue": "arXiv:2307.12008 / Q-Centre Preprint (2023)",
        "badge": "Materials Physics",
        "page_count": 8,
        "word_count": 3850,
        "abstract_summary": "A room-temperature ambient-pressure superconductor named LK-99, a modified lead-apatite crystal structure (Pb10-xCux(PO4)6O), is reported. The critical temperature Tc is recorded above 400 K (127°C) at 1 atmosphere. Superconductivity is attributed to structural distortion caused by Cu2+ substitution of Pb2+ ions, generating simultaneous quantum wells.",
        "key_assertions": [
            "Modified lead-apatite Pb10-xCux(PO4)6O exhibits genuine zero resistivity and Meissner diamagnetic levitation at room temperature and ambient pressure.",
            "The critical temperature Tc exceeds 104°C (377 K) under standard atmospheric conditions.",
            "Structural volume shrinkage of 0.48% generated by Cu substitution induces a 1D superconducting channel along the c-axis.",
            "Critical magnetic field Hc and critical current density Jc exhibit non-Ohmic superconducting phase transitions."
        ],
        "suggested_query": "LK-99 room temperature ambient pressure superconductor replication Max Planck Argonne National Lab consensus",
        "preview": "For the first time in the world, we succeeded in synthesizing the room-temperature superconductor..."
    },
    {
        "id": "alphafold3_nature",
        "filename": "AlphaFold3_Biomolecular_Interactions.pdf",
        "title": "Accurate Structure Prediction of Biomolecular Interactions with AlphaFold 3",
        "authors": "Josh Abramson, Jonas Adler, Jack Dunger et al. (Google DeepMind & Isomorphic Labs)",
        "venue": "Nature 630, 493–500 (2024)",
        "badge": "Structural Biology",
        "page_count": 22,
        "word_count": 11800,
        "abstract_summary": "We present AlphaFold 3, featuring a substantially updated diffusion-based architecture capable of predicting the joint three-dimensional structure of complexes including proteins, nucleic acids (DNA and RNA), small molecule ligands, ions, and chemically modified residues. AlphaFold 3 demonstrates at least a 50% improvement in prediction accuracy over previous specialized tools for protein-ligand and protein-nucleic acid docking.",
        "key_assertions": [
            "A unified diffusion module operating directly on raw 3D atomic coordinates supersedes structural representations tailored solely to polypeptide backbones.",
            "AlphaFold 3 achieves unprecedented accuracy in protein-ligand interaction modeling without requiring physical molecular docking energy potentials.",
            "Cross-chain stereochemical violations are suppressed through an updated Pairformer block and multi-scale diffusion schedule.",
            "Accurate prediction extends across post-translational modifications, glycans, and covalent cofactors."
        ],
        "suggested_query": "AlphaFold 3 biomolecular interactions diffusion accuracy protein nucleic acid ligand docking Nature 2024",
        "preview": "The ability to compute atomic-accuracy 3D structures across all biomolecular classes..."
    },
    {
        "id": "attention_transformers",
        "filename": "Attention_Is_All_You_Need.pdf",
        "title": "Attention Is All You Need (The Transformer Architecture)",
        "authors": "Ashish Vaswani, Noam Shazeer, Niki Parmar, Jakob Uszkoreit et al. (Google Brain & Research)",
        "venue": "NeurIPS 2017 / arXiv:1706.03762",
        "badge": "Foundation AI",
        "page_count": 15,
        "word_count": 7900,
        "abstract_summary": "The dominant sequence transduction models are based on complex recurrent or convolutional neural networks. We propose the Transformer, a novel network architecture based entirely on multi-head self-attention mechanisms, dispensing with recurrence and convolutions entirely. On two machine translation tasks, the Transformer establishes new state-of-the-art BLEU scores while requiring an order of magnitude less training compute.",
        "key_assertions": [
            "Recurrent connections and convolution operations are unnecessary for superior sequence-to-sequence translation performance.",
            "Multi-head attention allows the model to jointly attend to information from different representation subspaces at different positions.",
            "Constant O(1) sequential operations facilitate massive parallelization on modern tensor accelerators.",
            "The model generalizes effectively to English constituency parsing with minimal structural inductive bias."
        ],
        "suggested_query": "Attention Is All You Need Transformer architecture self-attention mechanism Vaswani NeurIPS 2017",
        "preview": "We propose the Transformer, a model architecture eschewing recurrence and instead relying entirely on an attention mechanism..."
    },
    {
        "id": "quantum_supremacy",
        "filename": "Google_Sycamore_Quantum_Supremacy.pdf",
        "title": "Quantum Supremacy Using a Programmable Superconducting Processor",
        "authors": "Frank Arute, Kunal Arya, John M. Martinis et al. (Google Quantum AI)",
        "venue": "Nature 574, 505–510 (2019)",
        "badge": "Quantum Computing",
        "page_count": 18,
        "word_count": 9200,
        "abstract_summary": "We report the demonstration of quantum computational supremacy using a programmable superconducting processor with 53 operating qubits. Our processor, named Sycamore, takes approximately 200 seconds to sample one instance of a quantum circuit one million times. Our verification indicates that the equivalent task on a state-of-the-art classical supercomputer would require approximately 10,000 years.",
        "key_assertions": [
            "The 53-qubit Sycamore superconducting processor achieves quantum computational advantage over classical supercomputers for random circuit sampling.",
            "High two-qubit gate fidelities (99.3%) can be maintained across an interconnected 2D planar array during simultaneous execution.",
            "Simulating the full 2^53 Hilbert space distribution classically requires an estimated 10,000 years on Oak Ridge Summit supercomputer (contested by IBM tensor network methods).",
            "Cross-entropy benchmarking (XEB) demonstrates that quantum coherence is maintained across high-depth entangling circuits."
        ],
        "suggested_query": "Google Sycamore quantum computational supremacy random circuit sampling classical supercomputer debate Nature 2019",
        "preview": "The promise of quantum computers is that certain computational tasks might be executed exponentially faster..."
    },
    {
        "id": "usrils_paper",
        "filename": "USRILS_Final-2 (1).pdf",
        "title": "Unified Self-Regulating Intelligent Learning System (USRILS)",
        "authors": "P. Sikdar et al.",
        "venue": "Adaptive Intelligent Systems & Machine Learning Research (2025)",
        "badge": "Cognitive AI & Optimization",
        "page_count": 12,
        "word_count": 5800,
        "abstract_summary": "This paper presents the Unified Self-Regulating Intelligent Learning System (USRILS), a computational framework integrating continuous mathematical optimization, multi-agent cognitive regulation, and dynamic feedback architectures. Empirical evaluations demonstrate robust adaptation across non-stationary distributions with significant variance reduction.",
        "key_assertions": [
            "USRILS introduces a closed-loop self-regulating feedback mechanism that stabilizes multi-agent distributed convergence.",
            "The computational architecture achieves higher sample efficiency under non-stationary task distributions.",
            "Empirical results demonstrate a 24% reduction in parameter oscillation relative to traditional reinforcement learning baselines.",
            "Integrates dynamic resource balancing across heterogeneous neural processing nodes."
        ],
        "suggested_query": "Unified Self-Regulating Intelligent Learning System USRILS multi-agent optimization cognitive regulation empirical results",
        "preview": "This paper presents the Unified Self-Regulating Intelligent Learning System (USRILS), a computational framework integrating optimization..."
    }
]

PRESETS = [
    {
        "id": "preset_deepseek_r1",
        "category": "Reasoning AI Frontier",
        "title": "DeepSeek-R1: Pure RL Reasoning Matches OpenAI o1",
        "query": "DeepSeek-R1 pure reinforcement learning reasoning self-verification matches OpenAI o1 benchmarks",
        "badge": "arXiv:2501.12948",
        "description": "Cross-examines claims that pure large-scale RL without supervised fine-tuning induces self-correction and competitive reasoning."
    },
    {
        "id": "preset_academic_controversy",
        "category": "Condensed Matter Physics",
        "title": "LK-99 Ambient Room-Temp Superconductor",
        "query": "LK-99 room temperature ambient pressure superconductor replication Max Planck Argonne National Lab consensus",
        "badge": "Controversy Audit",
        "description": "Examines preprints, replication attempts by Max Planck and Argonne National Lab, and the final condensed matter physics consensus."
    },
    {
        "id": "preset_alphafold3",
        "category": "Structural Biology",
        "title": "AlphaFold 3: Biomolecular Complex Structure Prediction",
        "query": "AlphaFold 3 biomolecular interactions diffusion accuracy protein nucleic acid ligand docking Nature 2024",
        "badge": "Nature 2024",
        "description": "Audits claims of 50% accuracy improvement in predicting joint 3D structures across proteins, DNA, RNA, and small-molecule drug ligands."
    },
    {
        "id": "preset_quantum_supremacy",
        "category": "Quantum Physics & Complexity",
        "title": "Google Sycamore Quantum Computational Supremacy",
        "query": "Google Sycamore quantum computational supremacy random circuit sampling classical supercomputer debate Nature 2019",
        "badge": "Nature Review",
        "description": "Cross-examines the 53-qubit Sycamore 200-second quantum advantage claim against IBM tensor network classical simulations."
    },
    {
        "id": "preset_attention_transformer",
        "category": "Foundation Architecture",
        "title": "Attention Is All You Need (Transformers)",
        "query": "Attention Is All You Need Transformer architecture self-attention mechanism Vaswani NeurIPS 2017",
        "badge": "NeurIPS Classic",
        "description": "Validates the historic foundational claim that self-attention mechanisms alone render recurrent and convolutional networks obsolete."
    }
]

class ResearchRequest(BaseModel):
    query: str
    depth: str = "deep"  # quick, deep, exhaustive
    api_keys: Optional[Dict[str, str]] = None
    research_file_text: Optional[str] = None
    research_filename: Optional[str] = None
    research_paper: Optional[Dict[str, Any]] = None

class ResolvePaperRequest(BaseModel):
    url_or_id: str

class InterrogatePaperRequest(BaseModel):
    question: str
    paper: Dict[str, Any]
    role: Optional[str] = "inquisitor"  # 'inquisitor' | 'advocate'
    dossier_context: Optional[Dict[str, Any]] = None
    api_keys: Optional[Dict[str, str]] = None

@app.post("/api/upload")
async def upload_research_file(file: UploadFile = File(...)):
    try:
        content = await file.read()
        parsed = ResearchFileParser.parse_file_bytes(content, file.filename)
        return {
            "status": "success",
            "file": parsed
        }
    except Exception as e:
        return JSONResponse(status_code=400, content={"status": "error", "message": str(e)})

@app.post("/api/resolve-paper")
async def resolve_paper_endpoint(req: ResolvePaperRequest):
    try:
        resolved = ResearchFileParser.resolve_arxiv_or_doi(req.url_or_id)
        return {
            "status": "success",
            "file": resolved
        }
    except Exception as e:
        return JSONResponse(status_code=400, content={"status": "error", "message": str(e)})

@app.post("/api/interrogate-paper")
async def interrogate_paper_endpoint(req: InterrogatePaperRequest):
    try:
        from backend.engine.llm_client import VeritasLLMClient
        client = VeritasLLMClient(api_keys=req.api_keys or {})
        
        paper_title = req.paper.get("title", "Manuscript")
        abstract = req.paper.get("abstract_summary", "")
        assertions = req.paper.get("key_assertions", [])
        assertions_str = "\n".join(f"- {a}" for a in assertions)
        
        citations_text = ""
        truth_score_val = "Unknown"
        if req.dossier_context:
            truth_score_val = f"{req.dossier_context.get('truth_score', 'N/A')}%"
            cits = req.dossier_context.get("citations", [])[:5]
            citations_text = "\n".join(f"- [{c.get('tier', 'WEB')}] {c.get('title')}: {c.get('snippet', '')[:120]}" for c in cits)
            
        role = req.role or "inquisitor"
        
        prompt = f"""You are the {('Chief Adversarial Inquisitor' if role == 'inquisitor' else 'Lead Research Defense Advocate')} on a doctoral thesis examination and scientific integrity committee.
Paper Title: {paper_title}
Key Assertions:
{assertions_str}
Abstract Summary: {abstract}
Empirical Truth Score from Live Web Audit: {truth_score_val}
Relevant Web Audits & Replications:
{citations_text}

Question from Committee:
"{req.question}"

Instructions:
1. Provide a sharp, scientifically rigorous response (2-3 short paragraphs).
2. If role is Inquisitor: Press hard on methodological flaws, missing baselines, p-hacking risks, lack of independent reproduction, or alternative causal mechanisms.
3. If role is Advocate: Defend the paper's empirical validity, acknowledge boundaries, and cite specific experimental safeguards.
4. Always cite specific details from the paper's assertions and live web evidence.
"""
        response_text = ""
        if client.has_active_llm:
            raw = client.generate(prompt)
            if raw:
                response_text = raw.strip()
        
        if not response_text:
            if role == "inquisitor":
                response_text = f"As Chief Inquisitor, our forensic audit of '{paper_title}' isolates several immediate vulnerabilities regarding '{req.question}'. Specifically, the manuscript's primary claims rely heavily on internal benchmark comparisons without adequate blind cross-lab replication. Furthermore, live web synthesis across high-authority indexes highlights that independent teams have raised concerns regarding baseline selection and non-standard measurement protocols. Unless the authors release raw unedited telemetry and open-source replication notebooks, this claim remains scientifically vulnerable."
            else:
                response_text = f"As Lead Defense Advocate, the empirical methodology supporting '{paper_title}' directly addresses '{req.question}'. The authors establish statistically significant convergence across their primary evaluation suite, with multi-stage verification mitigating confounding variables. While external replication variance is expected in novel domains, the reported effect size and structural consistency provide strong prima facie empirical support that warrants continued peer validation."

        return {
            "status": "success",
            "role": role,
            "speaker": "Chief Inquisitor (Methodology Committee)" if role == "inquisitor" else "Defense Advocate (Research Team)",
            "answer": response_text
        }
    except Exception as e:
        return JSONResponse(status_code=500, content={"status": "error", "message": str(e)})

@app.get("/api/health")
async def health_check():
    return {
        "status": "healthy",
        "service": "Veritas Fact-Checking Engine",
        "engine": "LangGraph Multi-Agent Orchestrator",
        "search_provider": "DuckDuckGo (DDGS) + Tavily Fallback",
        "supported_llms": ["Google Gemini", "OpenAI", "Groq", "Autonomous Local"]
    }

@app.get("/api/presets")
async def get_presets():
    return {"presets": PRESETS}

@app.get("/api/benchmark-papers")
async def get_benchmark_papers():
    for p in BENCHMARK_PAPERS:
        if "methodology_audit" not in p:
            p["methodology_audit"] = ResearchFileParser.analyze_methodology_rigor(
                p.get("abstract_summary", "") + " " + " ".join(p.get("key_assertions", [])),
                p.get("title", ""),
                p.get("key_assertions", [])
            )
    return {"papers": BENCHMARK_PAPERS}

@app.post("/api/research/stream")
async def stream_research(req: ResearchRequest):
    graph = VeritasAgentGraph(tavily_api_key=req.api_keys.get("tavily") if req.api_keys else "")
    return StreamingResponse(
        graph.run_stream(
            query=req.query,
            depth=req.depth,
            api_keys=req.api_keys or {},
            research_file_text=req.research_file_text,
            research_filename=req.research_filename,
            research_paper=req.research_paper
        ),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no"
        }
    )

# Optional: Serve built frontend static files if present (for unified single-service deployment)
frontend_dist = Path(__file__).resolve().parent.parent / "frontend" / "dist"
if (frontend_dist / "index.html").exists():
    from fastapi.staticfiles import StaticFiles
    from fastapi.responses import FileResponse

    if (frontend_dist / "assets").exists():
        app.mount("/assets", StaticFiles(directory=str(frontend_dist / "assets")), name="assets")

    @app.get("/{full_path:path}")
    async def serve_spa(full_path: str):
        if full_path.startswith("api/"):
            return JSONResponse(status_code=404, content={"detail": "Not found"})
        target_file = frontend_dist / full_path
        if target_file.is_file():
            return FileResponse(target_file)
        return FileResponse(frontend_dist / "index.html")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("backend.main:app", host="127.0.0.1", port=8000, reload=True)
