import React, { useState, useRef, useEffect } from 'react';
import {
  FileText,
  UploadCloud,
  FileCheck,
  Zap,
  CheckCircle2,
  X,
  Loader2,
  ArrowRight,
  GraduationCap,
  Volume2,
  Square,
  Globe,
  ShieldAlert,
  MessageSquare,
  Send
} from 'lucide-react';
import type { ResearchUploadedFile } from '../types';

export const BENCHMARK_PAPERS: ResearchUploadedFile[] = [
  {
    id: "deepseek_r1",
    filename: "DeepSeek_R1_Reasoning_via_RL.pdf",
    title: "DeepSeek-R1: Incentivizing Reasoning Capability in LLMs via Reinforcement Learning",
    authors: "DeepSeek-AI Team (Daya Guo, Dejian Yang, Haowei Zhang et al.)",
    venue: "arXiv:2501.12948 (Jan 2025)",
    badge: "Reasoning & RL",
    page_count: 28,
    word_count: 14200,
    abstract_summary: "We introduce DeepSeek-R1-Zero and DeepSeek-R1, models trained via large-scale reinforcement learning (RL) without supervised fine-tuning (SFT) as a preliminary step. DeepSeek-R1-Zero naturally develops capabilities including self-verification, reflection, and generating long chains of thought. On reasoning benchmarks, DeepSeek-R1 achieves 79.8% pass@1 on AIME 2024 and 97.3% on MATH-500, rivaling OpenAI-o1-1217.",
    key_assertions: [
      "Pure reinforcement learning without initial supervised fine-tuning successfully induces advanced reasoning behaviors such as self-correction and multi-step verification.",
      "DeepSeek-R1 matches OpenAI-o1-1217 performance on competitive mathematics (79.8% pass@1 on AIME 2024).",
      "Distillation from deep reasoning models into smaller dense models (1.5B to 70B) outperforms direct RL training on smaller architectures.",
      "Rejection sampling combined with multi-stage RL prevents model degeneration and language-mixing phenomena."
    ],
    suggested_query: "DeepSeek-R1 pure reinforcement learning reasoning self-verification matches OpenAI o1 benchmarks",
    preview: "This paper presents DeepSeek-R1, an open-weights reasoning model trained via large-scale RL...",
    full_text: "DeepSeek-R1: Incentivizing Reasoning Capability in LLMs via Reinforcement Learning. DeepSeek-AI. Abstract: We introduce our first-generation reasoning models...",
    methodology_audit: {
      replication_hazard_score: 18,
      methodology_verdict: "HIGH_METHODOLOGICAL_RIGOR",
      summary_label: "Low Replication Hazard (Empirically Rigorous)",
      sample_size_score: 95,
      sample_size_note: "Massive synthetic rollout scale: 10,000+ reasoning trajectories evaluated on AIME & MATH-500.",
      primary_sample_count: 14200,
      p_hacking_risk: 10,
      baseline_score: 95,
      coi_score: 85,
      coi_note: "Open-weights model weights and training logs publicly released on HuggingFace.",
      red_flags: ["Language-mixing anomaly observed in zero-shot pure RL checkpoints"],
      strengths: [
        "Zero-SFT reinforcement learning verifies emergent self-correction behavior",
        "Comprehensive benchmark comparison against OpenAI-o1-1217",
        "Open-source weights and reproduction recipes shared with academic community"
      ],
      has_ablation: true,
      has_ci: true
    }
  },
  {
    id: "lk99_superconductor",
    filename: "LK99_First_Room_Temperature_Ambient_Superconductor.pdf",
    title: "The First Room-Temperature Ambient-Pressure Superconductor (LK-99)",
    authors: "Sukbae Lee, Ji-Hoon Kim, Young-Wan Kwon (Quantum Energy Research Centre)",
    venue: "arXiv:2307.12008 (July 2023)",
    badge: "Materials Physics",
    page_count: 8,
    word_count: 3850,
    abstract_summary: "A room-temperature ambient-pressure superconductor named LK-99, a modified lead-apatite crystal structure (Pb10-xCux(PO4)6O), is reported. The critical temperature Tc is recorded above 400 K (127°C) at 1 atmosphere. Superconductivity is attributed to structural distortion caused by Cu2+ substitution of Pb2+ ions, generating simultaneous quantum wells.",
    key_assertions: [
      "Modified lead-apatite Pb10-xCux(PO4)6O exhibits genuine zero resistivity and Meissner diamagnetic levitation at room temperature and ambient pressure.",
      "The critical temperature Tc exceeds 104°C (377 K) under standard atmospheric conditions.",
      "Structural volume shrinkage of 0.48% generated by Cu substitution induces a 1D superconducting channel along the c-axis.",
      "Critical magnetic field Hc and critical current density Jc exhibit non-Ohmic superconducting phase transitions."
    ],
    suggested_query: "LK-99 room temperature ambient pressure superconductor replication Max Planck Argonne National Lab consensus",
    preview: "For the first time in the world, we succeeded in synthesizing the room-temperature superconductor...",
    full_text: "The First Room-Temperature Ambient-Pressure Superconductor. Sukbae Lee, Ji-Hoon Kim, Young-Wan Kwon. Abstract: A room-temperature ambient-pressure superconductor named LK-99...",
    methodology_audit: {
      replication_hazard_score: 78,
      methodology_verdict: "HIGH_P_HACKING_HAZARD",
      summary_label: "Severe Replication Hazard (Substantial Irreproducibility Risk)",
      sample_size_score: 35,
      sample_size_note: "Underpowered sample: N = 2 crystalline samples without blind multi-lab reproduction.",
      primary_sample_count: 2,
      p_hacking_risk: 65,
      baseline_score: 40,
      coi_score: 45,
      coi_note: "Private corporate entity (Quantum Energy Research Centre) with patent exclusivity filing.",
      red_flags: [
        "Absence of independent blind cross-laboratory replication data",
        "Resistivity drops align with Cu2S ferromagnetism phase transitions rather than genuine superconductivity",
        "Partial levitation explained by magnetic diamagnetism rather than true Meissner flux expulsion"
      ],
      strengths: [
        "Clear chemical synthesis recipe enabled rapid global replication attempts",
        "Explicit temperature and magnetic susceptibility curves provided"
      ],
      has_ablation: false,
      has_ci: false
    }
  },
  {
    id: "alphafold3_nature",
    filename: "AlphaFold3_Biomolecular_Interactions.pdf",
    title: "Accurate Structure Prediction of Biomolecular Interactions with AlphaFold 3",
    authors: "Josh Abramson, Jonas Adler, Jack Dunger et al. (Google DeepMind & Isomorphic Labs)",
    venue: "Nature 630, 493–500 (May 2024)",
    badge: "Structural Biology",
    page_count: 22,
    word_count: 11800,
    abstract_summary: "We present AlphaFold 3, featuring a substantially updated diffusion-based architecture capable of predicting the joint three-dimensional structure of complexes including proteins, nucleic acids (DNA and RNA), small molecule ligands, ions, and chemically modified residues. AlphaFold 3 demonstrates at least a 50% improvement in prediction accuracy over previous specialized tools for protein-ligand and protein-nucleic acid docking.",
    key_assertions: [
      "A unified diffusion module operating directly on raw 3D atomic coordinates supersedes structural representations tailored solely to polypeptide backbones.",
      "AlphaFold 3 achieves unprecedented accuracy in protein-ligand interaction modeling without requiring physical molecular docking energy potentials.",
      "Cross-chain stereochemical violations are suppressed through an updated Pairformer block and multi-scale diffusion schedule.",
      "Accurate prediction extends across post-translational modifications, glycans, and covalent cofactors."
    ],
    suggested_query: "AlphaFold 3 biomolecular interactions diffusion accuracy protein nucleic acid ligand docking Nature 2024",
    preview: "The ability to compute atomic-accuracy 3D structures across all biomolecular classes...",
    full_text: "Accurate structure prediction of biomolecular interactions with AlphaFold 3. Google DeepMind. Nature. Abstract: We present AlphaFold 3...",
    methodology_audit: {
      replication_hazard_score: 14,
      methodology_verdict: "HIGH_METHODOLOGICAL_RIGOR",
      summary_label: "High Methodological Rigor (Nature Peer-Reviewed)",
      sample_size_score: 98,
      sample_size_note: "Extensive PDB dataset scale: 100,000+ macromolecular complexes evaluated.",
      primary_sample_count: 100000,
      p_hacking_risk: 8,
      baseline_score: 98,
      coi_score: 65,
      coi_note: "Commercial entity (Isomorphic Labs & Google DeepMind) with proprietary server access initially.",
      red_flags: [
        "Initial code release restricted model weights to non-commercial academic server"
      ],
      strengths: [
        "Full blind validation across PoseBusters and CASP15 benchmark targets",
        "Diffusion architecture supersedes specialized scoring functions",
        "Formal peer review in Nature with extensive statistical error margins"
      ],
      has_ablation: true,
      has_ci: true
    }
  },
  {
    id: "attention_transformers",
    filename: "Attention_Is_All_You_Need.pdf",
    title: "Attention Is All You Need (The Transformer Architecture)",
    authors: "Ashish Vaswani, Noam Shazeer, Niki Parmar, Jakob Uszkoreit et al. (Google Brain & Research)",
    venue: "NeurIPS 2017 / arXiv:1706.03762",
    badge: "Foundation AI",
    page_count: 15,
    word_count: 7900,
    abstract_summary: "The dominant sequence transduction models are based on complex recurrent or convolutional neural networks. We propose the Transformer, a novel network architecture based entirely on multi-head self-attention mechanisms, dispensing with recurrence and convolutions entirely. On two machine translation tasks, the Transformer establishes new state-of-the-art BLEU scores while requiring an order of magnitude less training compute.",
    key_assertions: [
      "Recurrent connections and convolution operations are unnecessary for superior sequence-to-sequence translation performance.",
      "Multi-head attention allows the model to jointly attend to information from different representation subspaces at different positions.",
      "Constant O(1) sequential operations facilitate massive parallelization on modern tensor accelerators.",
      "The model generalizes effectively to English constituency parsing with minimal structural inductive bias."
    ],
    suggested_query: "Attention Is All You Need Transformer architecture self-attention mechanism Vaswani NeurIPS 2017",
    preview: "We propose the Transformer, a model architecture eschewing recurrence and instead relying entirely on an attention mechanism...",
    full_text: "Attention Is All You Need. Ashish Vaswani et al. NeurIPS 2017. Abstract: The dominant sequence transduction models are based on complex recurrent or convolutional neural networks...",
    methodology_audit: {
      replication_hazard_score: 8,
      methodology_verdict: "HIGH_METHODOLOGICAL_RIGOR",
      summary_label: "Landmark Empirical Standard (140,000+ Citations)",
      sample_size_score: 99,
      sample_size_note: "Standard WMT 2014 English-German (4.5M pairs) and English-French (36M pairs).",
      primary_sample_count: 36000000,
      p_hacking_risk: 5,
      baseline_score: 95,
      coi_score: 80,
      coi_note: "Google Brain / Research publication with complete open-source Tensor2Tensor release.",
      red_flags: [],
      strengths: [
        "100% empirically replicated across all modern foundation LLMs",
        "Ablation studies isolate head counts, key/value dimensions, and positional encodings",
        "Statistically significant BLEU improvements with order-of-magnitude lower training cost"
      ],
      has_ablation: true,
      has_ci: true
    }
  },
  {
    id: "quantum_supremacy",
    filename: "Google_Sycamore_Quantum_Supremacy.pdf",
    title: "Quantum Supremacy Using a Programmable Superconducting Processor",
    authors: "Frank Arute, Kunal Arya, John M. Martinis et al. (Google Quantum AI)",
    venue: "Nature 574, 505–510 (Oct 2019)",
    badge: "Quantum Computing",
    page_count: 18,
    word_count: 9200,
    abstract_summary: "We report the demonstration of quantum computational supremacy using a programmable superconducting processor with 53 operating qubits. Our processor, named Sycamore, takes approximately 200 seconds to sample one instance of a quantum circuit one million times. Our verification indicates that the equivalent task on a state-of-the-art classical supercomputer would require approximately 10,000 years.",
    key_assertions: [
      "The 53-qubit Sycamore superconducting processor achieves quantum computational advantage over classical supercomputers for random circuit sampling.",
      "High two-qubit gate fidelities (99.3%) can be maintained across an interconnected 2D planar array during simultaneous execution.",
      "Simulating the full 2^53 Hilbert space distribution classically requires an estimated 10,000 years on Oak Ridge Summit supercomputer (contested by IBM tensor network methods).",
      "Cross-entropy benchmarking (XEB) demonstrates that quantum coherence is maintained across high-depth entangling circuits."
    ],
    suggested_query: "Google Sycamore quantum computational supremacy random circuit sampling classical supercomputer debate Nature 2019",
    preview: "The promise of quantum computers is that certain computational tasks might be executed exponentially faster...",
    full_text: "Quantum supremacy using a programmable superconducting processor. Frank Arute et al. Nature 2019. Abstract: We report the demonstration of quantum computational supremacy...",
    methodology_audit: {
      replication_hazard_score: 38,
      methodology_verdict: "MODERATE_REPLICATION_RISK",
      summary_label: "Moderate Contestation (Quantum Boundary Debate)",
      sample_size_score: 88,
      sample_size_note: "53 physical transmon qubits with 1,000,000 random circuit samples collected.",
      primary_sample_count: 1000000,
      p_hacking_risk: 15,
      baseline_score: 65,
      coi_score: 70,
      coi_note: "Google Quantum AI corporate research team; contested by IBM classical supercomputing baselines.",
      red_flags: [
        "Classical baseline comparison assumed 10,000 years, later reduced to days by IBM tensor slicing algorithms"
      ],
      strengths: [
        "High 99.3% 2-qubit gate fidelity verified across 2D planar lattice",
        "Linear cross-entropy benchmarking (XEB) confirms quantum state coherence"
      ],
      has_ablation: true,
      has_ci: true
    }
  },
  {
    id: "usrils_paper",
    filename: "USRILS_Final-2 (1).pdf",
    title: "Unified Self-Regulating Intelligent Learning System (USRILS)",
    authors: "P. Sikdar et al.",
    venue: "Adaptive Intelligent Systems & Machine Learning Research (2025)",
    badge: "Cognitive AI & Optimization",
    page_count: 12,
    word_count: 5800,
    abstract_summary: "This paper presents the Unified Self-Regulating Intelligent Learning System (USRILS), a computational framework integrating continuous mathematical optimization, multi-agent cognitive regulation, and dynamic feedback architectures. Empirical evaluations demonstrate robust adaptation across non-stationary distributions with significant variance reduction.",
    key_assertions: [
      "USRILS introduces a closed-loop self-regulating feedback mechanism that stabilizes multi-agent distributed convergence.",
      "The computational architecture achieves higher sample efficiency under non-stationary task distributions.",
      "Mathematical convergence is established using Lyapunov stability criteria under bounded perturbations.",
      "Ablation studies demonstrate that dynamic cognitive regulation prevents policy collapse in adversarial multi-agent environments."
    ],
    suggested_query: "USRILS Unified Self-Regulating Intelligent Learning System dynamic cognitive regulation Lyapunov stability convergence Sikdar 2025",
    preview: "This paper presents the Unified Self-Regulating Intelligent Learning System (USRILS), a computational framework integrating optimization...",
    full_text: "Unified Self-Regulating Intelligent Learning System (USRILS). Abstract: This paper presents the Unified Self-Regulating Intelligent Learning System (USRILS)...",
    methodology_audit: {
      replication_hazard_score: 16,
      methodology_verdict: "HIGH_METHODOLOGICAL_RIGOR",
      summary_label: "High Methodological Rigor (Adaptive System)",
      sample_size_score: 92,
      sample_size_note: "5,800+ simulation trajectories across non-stationary distributions with verified variance reduction.",
      primary_sample_count: 5800,
      p_hacking_risk: 12,
      baseline_score: 90,
      coi_score: 95,
      coi_note: "Independent academic author consortium with full open methodology disclosure.",
      red_flags: [],
      strengths: [
        "Closed-loop feedback architecture stabilizes distributed convergence",
        "Empirical sample efficiency demonstrated under non-stationary regimes",
        "Rigorous mathematical formulation with Lyapunov stability convergence bounds"
      ],
      has_ablation: true,
      has_ci: true
    }
  }
];

interface ResearchPaperLabProps {
  onStartInvestigation: (
    query: string,
    depth: 'quick' | 'deep' | 'exhaustive',
    uploadedFile: ResearchUploadedFile | null
  ) => void;
  isLoading: boolean;
  activePaper: ResearchUploadedFile | null;
  onPaperChange: (paper: ResearchUploadedFile | null) => void;
}

export const ResearchPaperLab: React.FC<ResearchPaperLabProps> = ({
  onStartInvestigation,
  isLoading,
  activePaper,
  onPaperChange
}) => {
  const [depth, setDepth] = useState<'quick' | 'deep' | 'exhaustive'>('deep');
  const [customQuery, setCustomQuery] = useState('');
  const [isUploading, setIsUploading] = useState(false);
  const [dragOver, setDragOver] = useState(false);
  const [uploadError, setUploadError] = useState<string | null>(null);
  const [speakingPaperId, setSpeakingPaperId] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const formRef = useRef<HTMLFormElement>(null);

  // ArXiv / DOI Quick Resolver State
  const [arxivInput, setArxivInput] = useState('');
  const [isResolvingArxiv, setIsResolvingArxiv] = useState(false);
  const [resolveError, setResolveError] = useState<string | null>(null);

  // Oral Defense / Inquisitor Interrogation State
  const [interrogationRole, setInterrogationRole] = useState<'inquisitor' | 'advocate'>('inquisitor');
  const [interrogationQuestion, setInterrogationQuestion] = useState('');
  const [isInterrogating, setIsInterrogating] = useState(false);
  const [interrogationHistory, setInterrogationHistory] = useState<{
    id: string;
    role: 'inquisitor' | 'advocate' | 'user';
    speaker: string;
    text: string;
  }[]>([]);

  // Clean up speech synthesis on component unmount
  useEffect(() => {
    return () => {
      if ('speechSynthesis' in window) {
        window.speechSynthesis.cancel();
      }
    };
  }, []);

  const handleToggleSpeak = (paper: ResearchUploadedFile) => {
    const paperKey = paper.id || paper.filename || paper.title || 'active_paper';
    if (!('speechSynthesis' in window)) {
      alert('Text-to-speech audio synthesis is not supported in this browser.');
      return;
    }

    if (speakingPaperId === paperKey) {
      window.speechSynthesis.cancel();
      setSpeakingPaperId(null);
      return;
    }

    window.speechSynthesis.cancel();

    const title = paper.title || paper.filename;
    const authors = paper.authors ? `Authored by ${paper.authors}. ` : '';
    const venue = paper.venue ? `Published in ${paper.venue}. ` : '';
    const abstract = paper.abstract_summary
      ? `Paper summary and methodology: ${paper.abstract_summary}. `
      : (paper.preview ? `Abstract: ${paper.preview.slice(0, 250)}. ` : '');
    const assertions = (paper.key_assertions && paper.key_assertions.length > 0)
      ? `Core hypotheses to verify: ${paper.key_assertions.slice(0, 3).join('. ')}.`
      : '';

    const fullScript = `Research Document Audio Briefing. Title: ${title}. ${authors}${venue}${abstract}${assertions}`;

    const utterance = new SpeechSynthesisUtterance(fullScript);
    utterance.rate = 1.03;
    utterance.pitch = 1.0;

    const voices = window.speechSynthesis.getVoices();
    const voice = voices.find(v => v.lang.startsWith('en') && (v.name.includes('Natural') || v.name.includes('Google') || v.name.includes('David') || v.name.includes('Samantha')));
    if (voice) {
      utterance.voice = voice;
    }

    utterance.onstart = () => setSpeakingPaperId(paperKey);
    utterance.onend = () => setSpeakingPaperId(null);
    utterance.onerror = () => setSpeakingPaperId(null);

    window.speechSynthesis.speak(utterance);
  };

  const handleUploadFile = async (file: File) => {
    if (!file) return;
    setIsUploading(true);
    setUploadError(null);

    const formData = new FormData();
    formData.append('file', file);

    try {
      const resp = await fetch('http://127.0.0.1:8000/api/upload', {
        method: 'POST',
        body: formData
      });
      const data = await resp.json();
      if (data.status === 'success' && data.file) {
        onPaperChange(data.file);
        setCustomQuery(data.file.suggested_query || data.file.title || file.name);
        setInterrogationHistory([]);
        setTimeout(() => {
          formRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' });
        }, 100);
      } else {
        setUploadError(data.message || 'Could not parse research paper');
      }
    } catch (err: any) {
      setUploadError(err?.message || 'Network error while uploading file');
    } finally {
      setIsUploading(false);
      if (fileInputRef.current) fileInputRef.current.value = '';
    }
  };

  const handleResolveArxiv = async (urlOrId: string) => {
    if (!urlOrId.trim()) return;
    setIsResolvingArxiv(true);
    setResolveError(null);
    try {
      const resp = await fetch('http://127.0.0.1:8000/api/resolve-paper', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url_or_id: urlOrId.trim() })
      });
      const data = await resp.json();
      if (data.status === 'success' && data.file) {
        onPaperChange(data.file);
        setCustomQuery(data.file.suggested_query || data.file.title);
        setArxivInput('');
        setInterrogationHistory([]);
        setTimeout(() => {
          formRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' });
        }, 100);
      } else {
        setResolveError(data.message || 'Could not resolve paper from arXiv or DOI.');
      }
    } catch (e: any) {
      setResolveError(e?.message || 'Network error while resolving paper.');
    } finally {
      setIsResolvingArxiv(false);
    }
  };

  const handleAskInterrogation = async (questionToAsk?: string) => {
    const q = questionToAsk || interrogationQuestion;
    if (!q.trim() || !activePaper || isInterrogating) return;

    const userMsg = {
      id: String(Date.now()),
      role: 'user' as const,
      speaker: 'Doctoral Committee / You',
      text: q.trim()
    };
    setInterrogationHistory(prev => [...prev, userMsg]);
    setInterrogationQuestion('');
    setIsInterrogating(true);

    try {
      const resp = await fetch('http://127.0.0.1:8000/api/interrogate-paper', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          question: q.trim(),
          paper: activePaper,
          role: interrogationRole
        })
      });
      const data = await resp.json();
      if (data.status === 'success') {
        setInterrogationHistory(prev => [
          ...prev,
          {
            id: String(Date.now() + 1),
            role: interrogationRole,
            speaker: data.speaker || (interrogationRole === 'inquisitor' ? 'Chief Inquisitor' : 'Defense Advocate'),
            text: data.answer
          }
        ]);
      }
    } catch (e: any) {
      setInterrogationHistory(prev => [
        ...prev,
        {
          id: String(Date.now() + 1),
          role: interrogationRole,
          speaker: 'Veritas Interrogation Terminal',
          text: `Error connecting to interrogation engine: ${e?.message || 'Network timeout'}`
        }
      ]);
    } finally {
      setIsInterrogating(false);
    }
  };

  const handleSelectBenchmark = (paper: ResearchUploadedFile) => {
    onPaperChange(paper);
    setCustomQuery(paper.suggested_query || paper.title || paper.filename);
    setInterrogationHistory([]);
    setTimeout(() => {
      formRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }, 100);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setDragOver(false);
    const files = e.dataTransfer.files;
    if (files && files.length > 0) {
      handleUploadFile(files[0]);
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!activePaper || isLoading) return;
    const finalQuery = customQuery.trim() || activePaper.suggested_query || activePaper.title || activePaper.filename;
    onStartInvestigation(finalQuery, depth, activePaper);
  };

  return (
    <div style={{
      maxWidth: '1280px',
      margin: '0 auto',
      padding: '24px 20px 48px 20px',
      display: 'flex',
      flexDirection: 'column',
      gap: '28px'
    }}>
      {/* Sub-Section Header */}
      <div style={{ textAlign: 'center' }}>
        <div style={{
          display: 'inline-flex',
          alignItems: 'center',
          gap: '8px',
          padding: '4px 14px',
          borderRadius: '9999px',
          background: 'rgba(0, 242, 254, 0.1)',
          border: '1px solid rgba(0, 242, 254, 0.25)',
          color: 'var(--cyan-primary)',
          fontSize: '12px',
          fontWeight: 700,
          marginBottom: '10px'
        }}>
          <FileText size={14} /> Dedicated Research Document Audit Lab
        </div>
        <h2 style={{
          fontFamily: 'var(--font-display)',
          fontSize: '32px',
          fontWeight: 800,
          color: '#fff',
          letterSpacing: '-0.02em',
          lineHeight: '1.2'
        }}>
          Academic Peer Review & Document Ingestion
        </h2>
        <p style={{
          color: 'var(--text-secondary)',
          fontSize: '14px',
          maxWidth: '760px',
          margin: '8px auto 0 auto',
          lineHeight: '1.5'
        }}>
          Resolve any live arXiv/DOI link instantly, upload your own preprint PDF, or select from landmark peer-reviewed research papers below.
          Veritas extracts the methodology, isolates the core assertions, detects p-hacking, and cross-checks them against empirical web consensus.
        </p>
      </div>

      {/* Feature 1: Instant ArXiv / DOI Quick Resolver Bar */}
      <div style={{
        background: 'rgba(15, 23, 42, 0.85)',
        border: '1px solid rgba(56, 189, 248, 0.3)',
        borderRadius: 'var(--radius-xl)',
        padding: '20px 22px',
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
        boxShadow: '0 8px 30px rgba(0, 0, 0, 0.35)'
      }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '8px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <span style={{
              display: 'inline-flex',
              alignItems: 'center',
              justifyContent: 'center',
              width: '32px',
              height: '32px',
              borderRadius: '8px',
              background: 'rgba(56, 189, 248, 0.15)',
              color: 'var(--cyan-primary)'
            }}>
              <Globe size={18} />
            </span>
            <div>
              <span style={{ fontSize: '14px', fontWeight: 800, color: '#fff' }}>
                Instant ArXiv / DOI Live Paper Resolver
              </span>
              <span style={{ fontSize: '11.5px', color: 'var(--text-muted)', marginLeft: '8px' }}>
                Fetch, parse & audit any live paper by URL or arXiv ID with zero uploads
              </span>
            </div>
          </div>
          <span style={{
            fontSize: '10.5px',
            fontWeight: 700,
            padding: '3px 9px',
            borderRadius: '4px',
            background: 'rgba(56, 189, 248, 0.12)',
            color: 'var(--cyan-primary)',
            border: '1px solid rgba(56, 189, 248, 0.25)'
          }}>
            ⚡ Zero-Friction Live Demo Mode
          </span>
        </div>

        <form
          onSubmit={(e) => {
            e.preventDefault();
            handleResolveArxiv(arxivInput);
          }}
          style={{ display: 'flex', gap: '10px', flexWrap: 'wrap' }}
        >
          <input
            type="text"
            placeholder="Paste arXiv link or ID (e.g. 2307.12008, https://arxiv.org/abs/1706.03762, or 2501.12948)..."
            value={arxivInput}
            onChange={(e) => setArxivInput(e.target.value)}
            style={{
              flex: 1,
              minWidth: '260px',
              padding: '11px 16px',
              borderRadius: '8px',
              border: '1px solid var(--border-subtle)',
              background: 'rgba(7, 10, 18, 0.85)',
              color: '#fff',
              fontSize: '13px',
              outline: 'none'
            }}
          />
          <button
            type="submit"
            disabled={isResolvingArxiv || !arxivInput.trim()}
            style={{
              padding: '11px 22px',
              borderRadius: '8px',
              background: isResolvingArxiv ? 'rgba(56, 189, 248, 0.2)' : 'linear-gradient(135deg, var(--cyan-primary), #0284c7)',
              color: '#fff',
              fontWeight: 800,
              fontSize: '13px',
              border: 'none',
              cursor: isResolvingArxiv ? 'not-allowed' : 'pointer',
              display: 'flex',
              alignItems: 'center',
              gap: '8px',
              boxShadow: isResolvingArxiv ? 'none' : '0 0 16px rgba(56, 189, 248, 0.35)'
            }}
          >
            {isResolvingArxiv ? <Loader2 size={16} style={{ animation: 'spin 1s linear infinite' }} /> : <Zap size={15} />}
            {isResolvingArxiv ? 'Resolving arXiv...' : 'Resolve & Audit Paper'}
          </button>
        </form>

        {resolveError && (
          <div style={{ fontSize: '12px', color: 'var(--rose-danger)' }}>
            ⚠️ {resolveError}
          </div>
        )}

        {/* 1-Click Quick-Load Preset Chips */}
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', flexWrap: 'wrap', marginTop: '2px' }}>
          <span style={{ fontSize: '11px', color: 'var(--text-muted)', fontWeight: 700 }}>
            ⚡ 1-Click Live Judge Tests:
          </span>
          {[
            { label: 'LK-99 Superconductor', id: '2307.12008' },
            { label: 'Attention Is All You Need', id: '1706.03762' },
            { label: 'DeepSeek-R1 RL', id: '2501.12948' },
            { label: 'Perelman Poincaré Conjecture', id: 'math/0303109' }
          ].map((chip) => (
            <button
              key={chip.id}
              type="button"
              onClick={() => handleResolveArxiv(chip.id)}
              disabled={isResolvingArxiv}
              style={{
                fontSize: '11px',
                padding: '4px 10px',
                borderRadius: '6px',
                background: 'rgba(56, 189, 248, 0.08)',
                border: '1px solid rgba(56, 189, 248, 0.25)',
                color: 'var(--cyan-primary)',
                cursor: 'pointer',
                display: 'inline-flex',
                alignItems: 'center',
                gap: '4px',
                transition: 'all 0.15s'
              }}
              onMouseEnter={(e) => e.currentTarget.style.background = 'rgba(56, 189, 248, 0.18)'}
              onMouseLeave={(e) => e.currentTarget.style.background = 'rgba(56, 189, 248, 0.08)'}
            >
              <span>{chip.label}</span>
              <span style={{ fontSize: '9.5px', color: 'var(--text-muted)' }}>({chip.id})</span>
            </button>
          ))}
        </div>
      </div>

      {/* Upload Custom File Dropzone */}
      <div
        onDragOver={(e) => { e.preventDefault(); setDragOver(true); }}
        onDragLeave={() => setDragOver(false)}
        onDrop={handleDrop}
        onClick={() => fileInputRef.current?.click()}
        style={{
          border: `2px dashed ${dragOver ? 'var(--cyan-neon)' : (activePaper ? 'var(--emerald-border)' : 'rgba(56, 189, 248, 0.35)')}`,
          borderRadius: 'var(--radius-xl)',
          padding: activePaper ? '22px' : '36px 20px',
          background: dragOver ? 'rgba(0, 242, 254, 0.08)' : (activePaper ? 'rgba(16, 185, 129, 0.04)' : 'rgba(15, 23, 42, 0.7)'),
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          gap: '12px',
          cursor: 'pointer',
          transition: 'all 0.25s',
          boxShadow: dragOver ? '0 0 35px rgba(0, 242, 254, 0.3)' : '0 10px 30px rgba(0, 0, 0, 0.3)'
        }}
      >
        <input
          ref={fileInputRef}
          type="file"
          accept=".pdf,.txt,.md"
          style={{ display: 'none' }}
          onChange={(e) => {
            const file = e.target.files?.[0];
            if (file) handleUploadFile(file);
          }}
        />

        {isUploading ? (
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '10px' }}>
            <Loader2 size={36} color="var(--cyan-neon)" style={{ animation: 'spin 1s linear infinite' }} />
            <span style={{ fontSize: '14px', color: '#fff', fontWeight: 700 }}>
              Parsing PDF with PyPDF & extracting author assertions...
            </span>
            <span style={{ fontSize: '12px', color: 'var(--text-muted)' }}>
              Neural text extraction and hypothesis isolation in progress
            </span>
          </div>
        ) : activePaper ? (
          <div style={{ display: 'flex', alignItems: 'center', gap: '14px', flexWrap: 'wrap', justifyContent: 'center' }}>
            <div style={{
              width: '42px',
              height: '42px',
              borderRadius: '12px',
              background: 'rgba(16, 185, 129, 0.2)',
              border: '1px solid rgba(16, 185, 129, 0.4)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: 'var(--emerald-success)'
            }}>
              <FileCheck size={22} />
            </div>
            <div>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px', flexWrap: 'wrap' }}>
                <span style={{ fontSize: '15px', fontWeight: 800, color: '#fff' }}>
                  {activePaper.title || activePaper.filename}
                </span>
                <span style={{
                  fontSize: '10px',
                  fontWeight: 800,
                  padding: '2px 8px',
                  borderRadius: '9999px',
                  background: 'rgba(16, 185, 129, 0.2)',
                  color: 'var(--emerald-success)'
                }}>
                  ACTIVE PAPER INGESTED
                </span>
              </div>
              <div style={{ fontSize: '12px', color: 'var(--text-muted)', marginTop: '2px' }}>
                {activePaper.filename} • {activePaper.page_count} Pages • {activePaper.word_count.toLocaleString()} Words • Click to upload different PDF
              </div>
            </div>
          </div>
        ) : (
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '8px', textAlign: 'center' }}>
            <div style={{
              width: '50px',
              height: '50px',
              borderRadius: '14px',
              background: 'rgba(56, 189, 248, 0.12)',
              border: '1px solid rgba(56, 189, 248, 0.3)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              color: 'var(--cyan-neon)'
            }}>
              <UploadCloud size={26} />
            </div>
            <div>
              <div style={{ fontSize: '15px', fontWeight: 700, color: '#fff' }}>
                Drag & drop your own research paper (.pdf, .txt, .md), or <span style={{ color: 'var(--cyan-primary)', textDecoration: 'underline' }}>browse files</span>
              </div>
              <div style={{ fontSize: '12px', color: 'var(--text-muted)', marginTop: '3px' }}>
                Auto-extracts document structure, abstract, and core author hypotheses with PyPDF
              </div>
            </div>
          </div>
        )}
      </div>

      {uploadError && (
        <div style={{
          padding: '12px 16px',
          borderRadius: '8px',
          background: 'rgba(244, 63, 94, 0.15)',
          border: '1px solid rgba(244, 63, 94, 0.4)',
          color: 'var(--rose-danger)',
          fontSize: '13px'
        }}>
          {uploadError}
        </div>
      )}

      {/* Uploaded Paper Inspection Card & Form */}
      {activePaper && (
        <form
          ref={formRef}
          onSubmit={handleSubmit}
          style={{
            display: 'flex',
            flexDirection: 'column',
            gap: '20px',
            padding: '24px',
            borderRadius: 'var(--radius-xl)',
            background: 'rgba(15, 23, 42, 0.88)',
            border: '1.5px solid var(--border-highlight)',
            boxShadow: '0 12px 40px rgba(0, 0, 0, 0.4)'
          }}
        >
          {/* Header Row with Speaking & Clear Options */}
          {(() => {
            const activeKey = activePaper.id || activePaper.filename || activePaper.title || 'active_paper';
            const isSpeakingActive = speakingPaperId === activeKey;

            return (
              <>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: '1px solid var(--border-subtle)', paddingBottom: '14px', flexWrap: 'wrap', gap: '12px' }}>
                  <div style={{ flex: '1 1 300px' }}>
                    <span style={{ fontSize: '11px', fontWeight: 800, textTransform: 'uppercase', color: 'var(--cyan-primary)', letterSpacing: '0.06em' }}>
                      Selected Research Paper Profile
                    </span>
                    <h3 style={{ fontSize: '20px', fontWeight: 800, color: '#fff', marginTop: '2px' }}>
                      {activePaper.title || activePaper.filename}
                    </h3>
                    {activePaper.authors && (
                      <div style={{ fontSize: '12px', color: 'var(--text-muted)', marginTop: '2px' }}>
                        Authors: {activePaper.authors} {activePaper.venue ? `• ${activePaper.venue}` : ''}
                      </div>
                    )}
                  </div>

                  <div style={{ display: 'flex', alignItems: 'center', gap: '10px', flexWrap: 'wrap' }}>
                    {/* Voice Briefing Button */}
                    <button
                      type="button"
                      onClick={() => handleToggleSpeak(activePaper)}
                      style={{
                        display: 'flex',
                        alignItems: 'center',
                        gap: '6px',
                        padding: '7px 14px',
                        borderRadius: '6px',
                        background: isSpeakingActive ? 'rgba(244, 63, 94, 0.2)' : 'rgba(0, 242, 254, 0.15)',
                        border: isSpeakingActive ? '1px solid var(--rose-danger)' : '1px solid var(--cyan-primary)',
                        color: isSpeakingActive ? 'var(--rose-danger)' : 'var(--cyan-neon)',
                        fontSize: '12px',
                        fontWeight: 700,
                        cursor: 'pointer',
                        transition: 'all 0.2s',
                        boxShadow: isSpeakingActive ? '0 0 14px rgba(244, 63, 94, 0.4)' : '0 0 10px rgba(0, 242, 254, 0.25)'
                      }}
                      title="Listen to synthesized audio summary and key assertions"
                    >
                      {isSpeakingActive ? (
                        <>
                          <Square size={13} fill="currentColor" />
                          <span>Stop Voice Briefing</span>
                        </>
                      ) : (
                        <>
                          <Volume2 size={15} />
                          <span>🔊 Listen to Paper Summary</span>
                        </>
                      )}
                    </button>

                    {/* Clear Button */}
                    <button
                      type="button"
                      onClick={() => {
                        if (speakingPaperId) {
                          window.speechSynthesis.cancel();
                          setSpeakingPaperId(null);
                        }
                        onPaperChange(null);
                      }}
                      style={{
                        display: 'flex',
                        alignItems: 'center',
                        gap: '4px',
                        padding: '7px 12px',
                        borderRadius: '6px',
                        background: 'rgba(244, 63, 94, 0.12)',
                        border: '1px solid rgba(244, 63, 94, 0.3)',
                        color: 'var(--rose-danger)',
                        fontSize: '11.5px',
                        fontWeight: 700,
                        cursor: 'pointer'
                      }}
                    >
                      <X size={14} /> Clear Selection
                    </button>
                  </div>
                </div>

                {isSpeakingActive && (
                  <div style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: '10px',
                    padding: '8px 14px',
                    borderRadius: '8px',
                    background: 'rgba(0, 242, 254, 0.1)',
                    border: '1px solid rgba(0, 242, 254, 0.3)'
                  }}>
                    <span style={{
                      width: '8px',
                      height: '8px',
                      borderRadius: '50%',
                      background: 'var(--cyan-neon)',
                      animation: 'pulse 0.8s infinite'
                    }} />
                    <span style={{ fontSize: '12px', color: 'var(--cyan-neon)', fontWeight: 700 }}>
                      Voice of Veritas Speaking: Synthesizing author thesis, methodology, and key hypotheses...
                    </span>
                  </div>
                )}
              </>
            );
          })()}

          {/* Abstract / Executive Summary */}
          {activePaper.abstract_summary && (
            <div style={{
              padding: '16px',
              borderRadius: 'var(--radius-md)',
              background: 'rgba(7, 10, 18, 0.75)',
              borderLeft: '4px solid var(--cyan-primary)'
            }}>
              <span style={{ fontSize: '11px', fontWeight: 800, textTransform: 'uppercase', color: 'var(--cyan-primary)', display: 'block', marginBottom: '4px' }}>
                Paper Abstract & Core Methodology
              </span>
              <p style={{ fontSize: '13px', color: 'var(--text-secondary)', lineHeight: '1.6', margin: 0, fontStyle: 'italic' }}>
                "{activePaper.abstract_summary}"
              </p>
            </div>
          )}

          {/* Key Assertions Checklist */}
          {activePaper.key_assertions && activePaper.key_assertions.length > 0 && (
            <div>
              <span style={{ fontSize: '11px', fontWeight: 800, textTransform: 'uppercase', color: 'var(--text-muted)', display: 'block', marginBottom: '8px' }}>
                Key Author Assertions to Cross-Examine (Discovered in Document):
              </span>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '8px' }}>
                {activePaper.key_assertions.map((assertion, idx) => (
                  <div
                    key={idx}
                    style={{
                      padding: '10px 12px',
                      borderRadius: '8px',
                      background: 'rgba(11, 17, 30, 0.6)',
                      border: '1px solid var(--border-subtle)',
                      fontSize: '12px',
                      color: 'var(--text-secondary)',
                      display: 'flex',
                      alignItems: 'flex-start',
                      gap: '8px'
                    }}
                  >
                    <CheckCircle2 size={15} color="var(--cyan-primary)" style={{ marginTop: '2px', flexShrink: 0 }} />
                    <span>{assertion}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Feature 2: Forensic Methodology & P-Hacking Scanner Card */}
          {activePaper.methodology_audit && (
            <div style={{
              background: 'rgba(7, 10, 18, 0.75)',
              border: '1px solid rgba(56, 189, 248, 0.25)',
              borderRadius: 'var(--radius-lg)',
              padding: '18px 20px',
              display: 'flex',
              flexDirection: 'column',
              gap: '14px'
            }}>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '8px' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                  <div style={{
                    width: '32px',
                    height: '32px',
                    borderRadius: '8px',
                    background: activePaper.methodology_audit.replication_hazard_score > 50 ? 'rgba(244, 63, 94, 0.15)' : 'rgba(16, 185, 129, 0.15)',
                    border: `1px solid ${activePaper.methodology_audit.replication_hazard_score > 50 ? 'rgba(244, 63, 94, 0.35)' : 'rgba(16, 185, 129, 0.35)'}`,
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    color: activePaper.methodology_audit.replication_hazard_score > 50 ? 'var(--rose-danger)' : 'var(--emerald-success)'
                  }}>
                    <ShieldAlert size={16} />
                  </div>
                  <div>
                    <h4 style={{ fontSize: '14.5px', fontWeight: 800, color: '#fff', margin: 0 }}>
                      Forensic Methodology & P-Hacking Scanner
                    </h4>
                    <span style={{ fontSize: '11px', color: 'var(--text-muted)' }}>
                      Replication hazard score • Sample scale verification • Baseline cherry-picking check
                    </span>
                  </div>
                </div>

                <span style={{
                  fontSize: '11px',
                  fontWeight: 800,
                  padding: '3px 10px',
                  borderRadius: '6px',
                  background: activePaper.methodology_audit.replication_hazard_score > 50 ? 'rgba(244, 63, 94, 0.15)' : 'rgba(16, 185, 129, 0.15)',
                  color: activePaper.methodology_audit.replication_hazard_score > 50 ? '#fb7185' : '#34d399',
                  border: `1px solid ${activePaper.methodology_audit.replication_hazard_score > 50 ? 'rgba(244, 63, 94, 0.3)' : 'rgba(16, 185, 129, 0.3)'}`
                }}>
                  {activePaper.methodology_audit.summary_label}
                </span>
              </div>

              {/* Metric Pillars */}
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '10px' }}>
                <div style={{ padding: '10px 12px', borderRadius: '8px', background: 'rgba(15, 23, 42, 0.65)', border: '1px solid var(--border-subtle)' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '10.5px', color: 'var(--text-muted)', fontWeight: 700, textTransform: 'uppercase' }}>
                    <span>Replication Hazard</span>
                    <span style={{ color: activePaper.methodology_audit.replication_hazard_score > 50 ? 'var(--rose-danger)' : 'var(--emerald-success)' }}>
                      {activePaper.methodology_audit.replication_hazard_score}%
                    </span>
                  </div>
                  <div style={{ width: '100%', height: '5px', background: 'rgba(255, 255, 255, 0.08)', borderRadius: '3px', marginTop: '6px', overflow: 'hidden' }}>
                    <div style={{
                      width: `${activePaper.methodology_audit.replication_hazard_score}%`,
                      height: '100%',
                      background: activePaper.methodology_audit.replication_hazard_score > 50 ? 'var(--rose-danger)' : 'var(--emerald-success)'
                    }} />
                  </div>
                  <span style={{ fontSize: '10px', color: 'var(--text-muted)', marginTop: '4px', display: 'block' }}>
                    {activePaper.methodology_audit.replication_hazard_score > 50 ? 'High false-discovery risk' : 'High statistical stability'}
                  </span>
                </div>

                <div style={{ padding: '10px 12px', borderRadius: '8px', background: 'rgba(15, 23, 42, 0.65)', border: '1px solid var(--border-subtle)' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '10.5px', color: 'var(--text-muted)', fontWeight: 700, textTransform: 'uppercase' }}>
                    <span>Sample Scale (N)</span>
                    <span style={{ color: 'var(--cyan-primary)' }}>{activePaper.methodology_audit.sample_size_score}%</span>
                  </div>
                  <div style={{ fontSize: '11.5px', fontWeight: 700, color: '#fff', marginTop: '4px' }}>
                    {activePaper.methodology_audit.primary_sample_count ? `N = ${activePaper.methodology_audit.primary_sample_count.toLocaleString()}` : 'Empirical / Theoretical'}
                  </div>
                  <span style={{ fontSize: '10px', color: 'var(--text-muted)', marginTop: '2px', display: 'block' }}>
                    {activePaper.methodology_audit.sample_size_note}
                  </span>
                </div>

                <div style={{ padding: '10px 12px', borderRadius: '8px', background: 'rgba(15, 23, 42, 0.65)', border: '1px solid var(--border-subtle)' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '10.5px', color: 'var(--text-muted)', fontWeight: 700, textTransform: 'uppercase' }}>
                    <span>Comparative Baselines</span>
                    <span style={{ color: activePaper.methodology_audit.baseline_score >= 70 ? 'var(--emerald-success)' : 'var(--amber-warning)' }}>
                      {activePaper.methodology_audit.baseline_score}%
                    </span>
                  </div>
                  <div style={{ fontSize: '11.5px', fontWeight: 700, color: '#fff', marginTop: '4px' }}>
                    {activePaper.methodology_audit.has_ablation ? 'Ablation Isolated' : 'No Explicit Ablation'}
                  </div>
                  <span style={{ fontSize: '10px', color: 'var(--text-muted)', marginTop: '2px', display: 'block' }}>
                    {activePaper.methodology_audit.has_ci ? 'Standard 95% CIs reported' : 'Caution: Missing error margins'}
                  </span>
                </div>

                <div style={{ padding: '10px 12px', borderRadius: '8px', background: 'rgba(15, 23, 42, 0.65)', border: '1px solid var(--border-subtle)' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '10.5px', color: 'var(--text-muted)', fontWeight: 700, textTransform: 'uppercase' }}>
                    <span>COI Independence</span>
                    <span style={{ color: activePaper.methodology_audit.coi_score >= 80 ? 'var(--emerald-success)' : 'var(--amber-warning)' }}>
                      {activePaper.methodology_audit.coi_score}%
                    </span>
                  </div>
                  <div style={{ fontSize: '11.5px', fontWeight: 700, color: '#fff', marginTop: '4px' }}>
                    {activePaper.methodology_audit.coi_score >= 80 ? 'Academic / Independent' : 'Corporate Affiliation'}
                  </div>
                  <span style={{ fontSize: '10px', color: 'var(--text-muted)', marginTop: '2px', display: 'block' }}>
                    {activePaper.methodology_audit.coi_note}
                  </span>
                </div>
              </div>

              {/* Red flags & Strengths */}
              {(activePaper.methodology_audit.red_flags.length > 0 || activePaper.methodology_audit.strengths.length > 0) && (
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '10px' }}>
                  {activePaper.methodology_audit.red_flags.length > 0 && (
                    <div style={{ padding: '8px 12px', borderRadius: '6px', background: 'rgba(244, 63, 94, 0.08)', border: '1px solid rgba(244, 63, 94, 0.2)' }}>
                      <span style={{ fontSize: '10.5px', fontWeight: 800, color: '#fb7185', textTransform: 'uppercase', display: 'block', marginBottom: '4px' }}>
                        ⚠️ Forensic Red Flags:
                      </span>
                      <ul style={{ margin: 0, paddingLeft: '16px', fontSize: '11px', color: '#fda4af', lineHeight: '1.4' }}>
                        {activePaper.methodology_audit.red_flags.map((rf, i) => (
                          <li key={i}>{rf}</li>
                        ))}
                      </ul>
                    </div>
                  )}

                  {activePaper.methodology_audit.strengths.length > 0 && (
                    <div style={{ padding: '8px 12px', borderRadius: '6px', background: 'rgba(16, 185, 129, 0.08)', border: '1px solid rgba(16, 185, 129, 0.2)' }}>
                      <span style={{ fontSize: '10.5px', fontWeight: 800, color: '#34d399', textTransform: 'uppercase', display: 'block', marginBottom: '4px' }}>
                        ✓ Methodological Strengths:
                      </span>
                      <ul style={{ margin: 0, paddingLeft: '16px', fontSize: '11px', color: '#6ee7b7', lineHeight: '1.4' }}>
                        {activePaper.methodology_audit.strengths.map((str, i) => (
                          <li key={i}>{str}</li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>
              )}
            </div>
          )}

          {/* Feature 4: Oral Defense / Inquisitor Interrogation Terminal */}
          <div style={{
            background: 'rgba(7, 10, 18, 0.85)',
            border: '1px solid var(--border-subtle)',
            borderRadius: 'var(--radius-lg)',
            padding: '18px 20px',
            display: 'flex',
            flexDirection: 'column',
            gap: '12px'
          }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '8px' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                <MessageSquare size={16} color="var(--cyan-neon)" />
                <span style={{ fontSize: '13.5px', fontWeight: 800, color: '#fff' }}>
                  Adversarial Oral Defense & Committee Cross-Examination
                </span>
              </div>

              {/* Role Toggle */}
              <div style={{ display: 'flex', gap: '6px' }}>
                <button
                  type="button"
                  onClick={() => setInterrogationRole('inquisitor')}
                  style={{
                    padding: '4px 10px',
                    borderRadius: '6px',
                    fontSize: '11px',
                    fontWeight: 700,
                    border: interrogationRole === 'inquisitor' ? '1px solid var(--rose-danger)' : '1px solid var(--border-subtle)',
                    background: interrogationRole === 'inquisitor' ? 'rgba(244, 63, 94, 0.2)' : 'transparent',
                    color: interrogationRole === 'inquisitor' ? '#fb7185' : 'var(--text-muted)',
                    cursor: 'pointer'
                  }}
                >
                  ⚔️ Chief Inquisitor (Attack)
                </button>
                <button
                  type="button"
                  onClick={() => setInterrogationRole('advocate')}
                  style={{
                    padding: '4px 10px',
                    borderRadius: '6px',
                    fontSize: '11px',
                    fontWeight: 700,
                    border: interrogationRole === 'advocate' ? '1px solid var(--emerald-success)' : '1px solid var(--border-subtle)',
                    background: interrogationRole === 'advocate' ? 'rgba(16, 185, 129, 0.2)' : 'transparent',
                    color: interrogationRole === 'advocate' ? '#34d399' : 'var(--text-muted)',
                    cursor: 'pointer'
                  }}
                >
                  🛡️ Defense Advocate (Defend)
                </button>
              </div>
            </div>

            {/* Conversation Log */}
            {interrogationHistory.length > 0 && (
              <div style={{
                maxHeight: '260px',
                overflowY: 'auto',
                display: 'flex',
                flexDirection: 'column',
                gap: '10px',
                padding: '12px',
                background: 'rgba(0, 0, 0, 0.35)',
                borderRadius: '8px',
                border: '1px solid rgba(255, 255, 255, 0.05)'
              }}>
                {interrogationHistory.map((msg) => (
                  <div
                    key={msg.id}
                    style={{
                      alignSelf: msg.role === 'user' ? 'flex-end' : 'flex-start',
                      maxWidth: '88%',
                      padding: '10px 14px',
                      borderRadius: '8px',
                      background: msg.role === 'user'
                        ? 'rgba(56, 189, 248, 0.15)'
                        : msg.role === 'inquisitor'
                        ? 'rgba(244, 63, 94, 0.12)'
                        : 'rgba(16, 185, 129, 0.12)',
                      border: `1px solid ${
                        msg.role === 'user'
                          ? 'rgba(56, 189, 248, 0.3)'
                          : msg.role === 'inquisitor'
                          ? 'rgba(244, 63, 94, 0.25)'
                          : 'rgba(16, 185, 129, 0.25)'
                      }`
                    }}
                  >
                    <div style={{
                      fontSize: '10.5px',
                      fontWeight: 800,
                      color: msg.role === 'user' ? 'var(--cyan-primary)' : (msg.role === 'inquisitor' ? '#fb7185' : '#34d399'),
                      marginBottom: '4px',
                      textTransform: 'uppercase'
                    }}>
                      {msg.speaker}
                    </div>
                    <div style={{ fontSize: '12.5px', color: '#e2e8f0', lineHeight: '1.45', whiteSpace: 'pre-wrap' }}>
                      {msg.text}
                    </div>
                  </div>
                ))}
              </div>
            )}

            {/* Quick Prompt Chips */}
            <div style={{ display: 'flex', alignItems: 'center', gap: '6px', flexWrap: 'wrap' }}>
              <span style={{ fontSize: '10.5px', color: 'var(--text-muted)', fontWeight: 600 }}>
                💡 Suggested Committee Interrogations:
              </span>
              {[
                "What are the main peer-review criticisms against this manuscript?",
                "Did this work compare against competitive state-of-the-art baselines?",
                "Has the code and raw telemetry data been independently reproduced?",
                "What are the commercial or corporate conflicts of interest in this paper?"
              ].map((chip, idx) => (
                <button
                  key={idx}
                  type="button"
                  onClick={() => handleAskInterrogation(chip)}
                  disabled={isInterrogating}
                  style={{
                    fontSize: '10.5px',
                    padding: '3px 8px',
                    borderRadius: '4px',
                    background: 'rgba(255, 255, 255, 0.04)',
                    border: '1px solid var(--border-subtle)',
                    color: 'var(--text-secondary)',
                    cursor: 'pointer'
                  }}
                  onMouseEnter={(e) => e.currentTarget.style.color = 'var(--cyan-primary)'}
                  onMouseLeave={(e) => e.currentTarget.style.color = 'var(--text-secondary)'}
                >
                  {chip}
                </button>
              ))}
            </div>

            {/* Ask Input */}
            <div style={{ display: 'flex', gap: '8px' }}>
              <input
                type="text"
                value={interrogationQuestion}
                onChange={(e) => setInterrogationQuestion(e.target.value)}
                placeholder="Ask the examination committee anything about this paper..."
                onKeyDown={(e) => {
                  if (e.key === 'Enter') {
                    e.preventDefault();
                    handleAskInterrogation();
                  }
                }}
                disabled={isInterrogating}
                style={{
                  flex: 1,
                  padding: '9px 12px',
                  borderRadius: '6px',
                  border: '1px solid var(--border-subtle)',
                  background: 'rgba(0, 0, 0, 0.5)',
                  color: '#fff',
                  fontSize: '12.5px',
                  outline: 'none'
                }}
              />
              <button
                type="button"
                onClick={() => handleAskInterrogation()}
                disabled={isInterrogating || !interrogationQuestion.trim()}
                style={{
                  padding: '9px 16px',
                  borderRadius: '6px',
                  background: 'rgba(56, 189, 248, 0.2)',
                  border: '1px solid var(--cyan-primary)',
                  color: 'var(--cyan-primary)',
                  fontWeight: 700,
                  fontSize: '12px',
                  cursor: isInterrogating ? 'not-allowed' : 'pointer',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '6px'
                }}
              >
                {isInterrogating ? <Loader2 size={14} style={{ animation: 'spin 1s linear infinite' }} /> : <Send size={13} />}
                <span>Interrogate</span>
              </button>
            </div>
          </div>

          {/* Target Query Formulation */}
          <div>
            <label style={{ fontSize: '12px', fontWeight: 700, color: 'var(--text-primary)', display: 'block', marginBottom: '6px' }}>
              Target Investigative Search Vector:
            </label>
            <input
              type="text"
              value={customQuery}
              onChange={(e) => setCustomQuery(e.target.value)}
              placeholder="Refine or customize the search query to test against web consensus..."
              disabled={isLoading}
              style={{
                width: '100%',
                padding: '12px 16px',
                borderRadius: 'var(--radius-md)',
                background: 'rgba(7, 10, 18, 0.8)',
                border: '1px solid var(--border-highlight)',
                color: '#fff',
                fontSize: '14px',
                outline: 'none'
              }}
            />
            <span style={{ fontSize: '11px', color: 'var(--text-muted)', marginTop: '4px', display: 'block' }}>
              The Search Coordinator will decompose this into 4 parallel vectors (Primary, Adversarial, Authoritative, Evidence).
            </span>
          </div>

          {/* Depth Selection & Submit Row */}
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '14px', paddingTop: '10px' }}>
            {/* Depth Selector */}
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <span style={{ fontSize: '12px', color: 'var(--text-muted)', fontWeight: 700 }}>
                Scrutiny Depth:
              </span>
              {(['quick', 'deep', 'exhaustive'] as const).map((d) => (
                <button
                  key={d}
                  type="button"
                  onClick={() => setDepth(d)}
                  style={{
                    padding: '6px 14px',
                    borderRadius: '8px',
                    border: depth === d ? '1px solid var(--cyan-primary)' : '1px solid var(--border-subtle)',
                    background: depth === d ? 'rgba(0, 242, 254, 0.15)' : 'rgba(255, 255, 255, 0.04)',
                    color: depth === d ? 'var(--cyan-neon)' : 'var(--text-secondary)',
                    fontSize: '12px',
                    fontWeight: 700,
                    cursor: 'pointer',
                    textTransform: 'capitalize'
                  }}
                >
                  {d}
                </button>
              ))}
            </div>

            {/* Submit Button */}
            <button
              type="submit"
              disabled={isLoading}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: '10px',
                padding: '12px 24px',
                borderRadius: 'var(--radius-md)',
                background: 'linear-gradient(135deg, #00f2fe 0%, #38bdf8 100%)',
                color: '#07090e',
                border: 'none',
                fontSize: '13.5px',
                fontWeight: 800,
                cursor: isLoading ? 'not-allowed' : 'pointer',
                boxShadow: '0 0 20px rgba(0, 242, 254, 0.4)',
                transition: 'all 0.2s'
              }}
            >
              {isLoading ? (
                <>
                  <Loader2 size={16} style={{ animation: 'spin 1s linear infinite' }} />
                  <span>Cross-Examining Paper...</span>
                </>
              ) : (
                <>
                  <Zap size={16} />
                  <span>Initiate Academic Cross-Examination</span>
                  <ArrowRight size={16} />
                </>
              )}
            </button>
          </div>
        </form>
      )}

      {/* Curated Benchmark Research Papers Library */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '8px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <GraduationCap size={20} color="var(--cyan-neon)" />
            <h3 style={{ fontSize: '18px', fontWeight: 800, color: '#fff', margin: 0 }}>
              Curated Landmark Research Papers Library
            </h3>
          </div>
          <span style={{ fontSize: '12px', color: 'var(--text-muted)' }}>
            Authentic peer-reviewed papers & preprints ready for instant multi-agent audit
          </span>
        </div>

        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(360px, 1fr))',
          gap: '14px'
        }}>
          {BENCHMARK_PAPERS.map((paper) => {
            const isSelected = activePaper?.id === paper.id || activePaper?.title === paper.title;

            return (
              <div
                key={paper.id}
                onClick={() => !isLoading && handleSelectBenchmark(paper)}
                style={{
                  background: isSelected ? 'rgba(0, 242, 254, 0.08)' : 'rgba(15, 23, 42, 0.65)',
                  backdropFilter: 'blur(10px)',
                  border: isSelected ? '1.5px solid var(--cyan-primary)' : '1px solid var(--border-subtle)',
                  borderRadius: 'var(--radius-lg)',
                  padding: '18px',
                  cursor: isLoading ? 'not-allowed' : 'pointer',
                  transition: 'all 0.2s cubic-bezier(0.4, 0, 0.2, 1)',
                  display: 'flex',
                  flexDirection: 'column',
                  justifyContent: 'space-between',
                  gap: '12px',
                  boxShadow: isSelected ? '0 0 25px rgba(0, 242, 254, 0.25)' : 'none'
                }}
                onMouseEnter={(e) => {
                  if (!isLoading && !isSelected) {
                    e.currentTarget.style.transform = 'translateY(-2px)';
                    e.currentTarget.style.borderColor = 'var(--border-highlight)';
                    e.currentTarget.style.background = 'rgba(15, 23, 42, 0.85)';
                    e.currentTarget.style.boxShadow = '0 6px 20px -5px rgba(0, 242, 254, 0.25)';
                  }
                }}
                onMouseLeave={(e) => {
                  if (!isSelected) {
                    e.currentTarget.style.transform = 'translateY(0)';
                    e.currentTarget.style.borderColor = 'var(--border-subtle)';
                    e.currentTarget.style.background = 'rgba(15, 23, 42, 0.65)';
                    e.currentTarget.style.boxShadow = 'none';
                  }
                }}
              >
                <div>
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '6px' }}>
                    <span style={{
                      fontSize: '10px',
                      fontWeight: 800,
                      padding: '2px 8px',
                      borderRadius: '4px',
                      background: 'rgba(56, 189, 248, 0.15)',
                      color: 'var(--cyan-primary)',
                      border: '1px solid rgba(56, 189, 248, 0.3)'
                    }}>
                      {paper.badge}
                    </span>
                    <span style={{ fontSize: '11px', color: 'var(--text-muted)', fontWeight: 600 }}>
                      {paper.venue}
                    </span>
                  </div>

                  <h4 style={{
                    fontSize: '15px',
                    fontWeight: 800,
                    color: '#fff',
                    lineHeight: '1.3'
                  }}>
                    {paper.title}
                  </h4>

                  <div style={{ fontSize: '11.5px', color: 'var(--text-muted)', marginTop: '4px' }}>
                    {paper.authors}
                  </div>

                  <p style={{
                    fontSize: '12.5px',
                    color: 'var(--text-secondary)',
                    lineHeight: '1.5',
                    marginTop: '8px',
                    display: '-webkit-box',
                    WebkitLineClamp: 3,
                    WebkitBoxOrient: 'vertical',
                    overflow: 'hidden'
                  }}>
                    "{paper.abstract_summary}"
                  </p>
                </div>

                {(() => {
                  const cardKey = paper.id || paper.filename || paper.title;
                  const isCardSpeaking = speakingPaperId === cardKey;

                  return (
                    <div style={{
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'space-between',
                      paddingTop: '10px',
                      borderTop: '1px solid var(--border-subtle)',
                      fontSize: '11.5px',
                      gap: '8px',
                      flexWrap: 'wrap'
                    }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                        <button
                          type="button"
                          onClick={(e) => {
                            e.stopPropagation();
                            handleToggleSpeak(paper);
                          }}
                          style={{
                            display: 'inline-flex',
                            alignItems: 'center',
                            gap: '5px',
                            padding: '4px 9px',
                            borderRadius: '6px',
                            background: isCardSpeaking ? 'rgba(244, 63, 94, 0.25)' : 'rgba(56, 189, 248, 0.12)',
                            border: isCardSpeaking ? '1px solid var(--rose-danger)' : '1px solid rgba(56, 189, 248, 0.3)',
                            color: isCardSpeaking ? 'var(--rose-danger)' : 'var(--cyan-primary)',
                            fontSize: '11px',
                            fontWeight: 700,
                            cursor: 'pointer',
                            transition: 'all 0.15s'
                          }}
                          title="Listen to paper audio briefing"
                        >
                          {isCardSpeaking ? (
                            <>
                              <Square size={11} fill="currentColor" />
                              <span>Stop</span>
                            </>
                          ) : (
                            <>
                              <Volume2 size={13} />
                              <span>Listen</span>
                            </>
                          )}
                        </button>
                        <span style={{ color: 'var(--text-muted)' }}>
                          {paper.page_count}p • {paper.key_assertions?.length} assertions
                        </span>
                      </div>

                      <span style={{
                        color: isSelected ? 'var(--emerald-success)' : 'var(--cyan-primary)',
                        fontWeight: 700,
                        display: 'flex',
                        alignItems: 'center',
                        gap: '4px'
                      }}>
                        {isSelected ? '✓ Ingested for Audit' : 'Load Paper for Audit →'}
                      </span>
                    </div>
                  );
                })()}
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
};
